pipes:
  pipe1:
    length: 0.01
    radius: 0.002
    particle_count: 0
    left_connections: []
    right_connections:
    - sink1
    flow: 0.00001
    receivers:
    - type: Ring type with thickness
      z: 0.000
      countingType: 0
      thickness: 0.0005
      name: '#1-Ring type with thickness'
    emitters:
    - z: -0.007
      r: 0.0
      theta: 0.0
      emitter_pattern: '1000'
      emitter_pattern_type: complete
    - z: +0.003
      r: 0.0
      theta: 0.0
      emitter_pattern: '1000'
      emitter_pattern_type: complete
sinks:
  sink1:
    left_connections:
    - pipe1
