pipes:
  pipe0:
    length: 0.1
    radius: 0.01
    particle_count: 0
    left_connections: []
    right_connections:
    - pipe1
    - pipe2
    flow: 1.0
  pipe1:
    length: 0.1
    radius: 0.02
    particle_count: 0
    left_connections:
    - pipe0
    right_connections: []
    flow: 0.9411764705882353
  pipe2:
    length: 0.1
    radius: 0.01
    particle_count: 0
    left_connections:
    - pipe0
    right_connections: []
    flow: 0.058823529411764705
