pipes:
  pipe1-a:
    length: 0.0008
    radius: 0.0003
    particle_count: 0
    left_connections: []
    right_connections:
    - sink1
    flow: 0.0001
    emitters:
    - z: 0.0
      r: 0.0
      theta: 0.0
      emitter_pattern: '1000'
      emitter_pattern_type: complete
sinks:
  sink1:
    left_connections:
    - pipe1-a
