pipes:
  pipe0:
    length: 0.0003
    radius: 3.0e-05
    particle_count: 0
    left_connections: []
    right_connections:
    - pipe2
    - pipe1
    flow: 1.0
    emitters:
    - z: 0.0
      r: 0.0
      theta: 0.0
      emitter_pattern: 10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
  pipe1:
    length: 0.0003
    radius: 3.0e-05
    particle_count: 0
    left_connections:
    - pipe0
    - pipe2
    right_connections: []
    flow: 0.11473087818696884
    receivers:
    - type: Trap (tangent)
      length: 0.1
      radius: 0.01
      theta: 0.0
      delta_theta: 0.0
  pipe2:
    length: 0.0003
    radius: 5.0e-05
    particle_count: 0
    left_connections:
    - pipe0
    right_connections:
    - pipe1
    flow: 0.8852691218130312
    receivers:
    - type: Trap (tangent)
      length: 0.1
      radius: 0.01
      theta: 0.0
      delta_theta: 0.0
