pipes:
  n0:
    left_connections: []
    length: 0.0007
    particle_count: 1000
    radius: 3.0e-05
    right_connections:
      - n1
      - n2
  n1:
    left_connections:
      - n0
    length: 0.0007
    particle_count: 0
    radius: 3.0e-05
    right_connections: []
  n2:
    left_connections:
      - n0
    length: 0.2
    particle_count: 0
    radius: 0.001
    right_connections: []
