pipes:
  pipe0:
    length: 0.0002
    radius: 0.0002
    particle_count: 0
    left_connections: []
    right_connections:
      - pipe1
  pipe1:
    length: 0.0002
    radius: 0.0002
    particle_count: 0
    left_connections:
      - pipe0
    right_connections: []
    receivers:
      - type: Ring type
        z: 0.0001
    emitters:
      - z: -0.0001
        r: 0.0
        theta: 0.0
        emitter_pattern: 10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
