pipes:
  pipe0:
    length: 0.0003
    radius: 0.0002
    particle_count: 1000
    left_connections: []
    right_connections:
      - pipe1
  pipe1:
    length: 0.0003
    radius: 0.0002
    particle_count: 0
    left_connections:
      - pipe0
    right_connections: []
    receivers:
      - type: Ring type
        z: 0.0
